#!/usr/bin/env ruby


if ARGV[0] && ARGV[1]
  require_relative 'lib/month'

  month = ARGV[0].to_i
  year = ARGV[1].to_i

  month = Month.new(month, year)
  puts month.to_s
elsif ARGV[0] && ARGV[0].length == 4
  require_relative 'lib/month'

  year = ARGV[0].to_i

  year = Year.new(year)
  puts year.to_s
end
